/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ChessIndexRouteImport } from './routes/chess/index'
import { Route as ChessSlugRouteImport } from './routes/chess/$slug'
import { Route as ChessArchiveRouteImport } from './routes/chess/archive'
import { Route as IssuesIdRouteImport } from './routes/issues/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessIndexRoute = ChessIndexRouteImport.update({
  id: '/chess/',
  path: '/chess/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessSlugRoute = ChessSlugRouteImport.update({
  id: '/chess/$slug',
  path: '/chess/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessArchiveRoute = ChessArchiveRouteImport.update({
  id: '/chess/archive',
  path: '/chess/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIdRoute = IssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/chess/$slug': typeof ChessSlugRoute
  '/chess/archive': typeof ChessArchiveRoute
  '/issues/$id': typeof IssuesIdRoute
  '/chess/': typeof ChessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/chess/$slug': typeof ChessSlugRoute
  '/chess/archive': typeof ChessArchiveRoute
  '/issues/$id': typeof IssuesIdRoute
  '/chess': typeof ChessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/chess/$slug': typeof ChessSlugRoute
  '/chess/archive': typeof ChessArchiveRoute
  '/issues/$id': typeof IssuesIdRoute
  '/chess/': typeof ChessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/review'
    | '/chess/$slug'
    | '/chess/archive'
    | '/issues/$id'
    | '/chess/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/review'
    | '/chess/$slug'
    | '/chess/archive'
    | '/issues/$id'
    | '/chess'
  id:
    | '__root__'
    | '/'
    | '/review'
    | '/chess/$slug'
    | '/chess/archive'
    | '/issues/$id'
    | '/chess/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewRoute: typeof ReviewRoute
  ChessSlugRoute: typeof ChessSlugRoute
  ChessArchiveRoute: typeof ChessArchiveRoute
  IssuesIdRoute: typeof IssuesIdRoute
  ChessIndexRoute: typeof ChessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess/': {
      id: '/chess/'
      path: '/chess'
      fullPath: '/chess/'
      preLoaderRoute: typeof ChessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess/$slug': {
      id: '/chess/$slug'
      path: '/chess/$slug'
      fullPath: '/chess/$slug'
      preLoaderRoute: typeof ChessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess/archive': {
      id: '/chess/archive'
      path: '/chess/archive'
      fullPath: '/chess/archive'
      preLoaderRoute: typeof ChessArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$id': {
      id: '/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof IssuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewRoute: ReviewRoute,
  ChessSlugRoute: ChessSlugRoute,
  ChessArchiveRoute: ChessArchiveRoute,
  IssuesIdRoute: IssuesIdRoute,
  ChessIndexRoute: ChessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
